name: Build plugin
run-name: ${{ github.actor }} is building the plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: ConorMacBride/install-package@v1
        with:
          apt: qttools5-dev-tools

      - name: Build translations
        working-directory: ValeLS/ts
        run: lrelease *.ts

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # Make a release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ValeLS/init.lua
            ValeLS/ValeLS.lua
            ValeLS/ts/*.qm

      - name: Release on Extension Store
        uses: Maddimax/deploy-lua-plugin@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          api: ${{ secrets.EXTENSION_STORE_API_URL }}
          token: ${{ secrets.EXTENSION_STORE_API_TOKEN }}
          spec: ValeLS/ValeLS.lua
          download-url: ${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }} 
