name: Build plugin
run-name: ${{ github.actor }} is building the plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Maddimax/install-qtc@v1
        with:
          version: '14.0.0'

      - uses: ConorMacBride/install-package@v1
        with:
          apt: qttools5-dev-tools

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build translations
        working-directory: ValeLS/ts
        run: lrelease *.ts

      - name: Upload Plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValeLS
          path: ./ValeLS*
