name: Build plugin
run-name: ${{ github.actor }} is building the plugin
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: ConorMacBride/install-package@v1
        with:
          apt: qttools5-dev-tools

      - name: Build translations
        working-directory: ValeLS/ts
        run: lrelease *.ts

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValeLS
          path: |
            ./ValeLS*
            !./ValeLS/**/*.ts
