name: Build plugin
run-name: ${{ github.actor }} is building the plugin
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: ConorMacBride/install-package@v1
        with:
          apt: qttools5-dev-tools

      - name: Build translations
        working-directory: ValeLS/ts
        run: lrelease *.ts
      
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValeLS
          path: |
            ./ValeLS*
            !./ValeLS/**/*.ts

      - name: Download artifact
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: ValeLS

      # Make a release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ${{ steps.download_artifact.outputs.download-path }}/ValeLS.zip

      - name: Release on Extension Store
        uses: Maddimax/deploy-lua-plugin@v2.6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          api: ${{ secrets.EXTENSION_STORE_API_URL }}
          token: ${{ secrets.EXTENSION_STORE_API_TOKEN }}
          spec: ValeLS/valels.lua
          download-url: ${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }} 
